apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kqlstore-api-data
  namespace: kqlstore
  labels:
    app: kqlstore-api
    app.kubernetes.io/managed-by: kustomize
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
