import { describe, expect, test } from 'vitest';
import { parseAzureMonitorTable } from '../fetch-schemas.js';

// Modelled on the real generated format of
// azure-monitor-docs/articles/azure-monitor/reference/tables/signinlogs.md.
const AZURE_FIXTURE = `---
title: Azure Monitor Logs reference - SigninLogs
ms.topic: generated-reference

# This file is automatically generated. Changes will be overwritten. Do not change this file directly.
---

# SigninLogs

## Table attributes

|Attribute|Value|
|---|---|
|**Resource types**|microsoft.graph/tenants|
|**Categories**|Azure Resources, Security|
|**Solutions**| LogManagement|

## Columns

| Column | Type | Description |
|---|---|---|
| AADTenantId | string |   |
| ConditionalAccessStatus | string | The status of the conditional access policy triggered. |
| DeviceDetail | dynamic | The device information from where the sign-in occurred. |
| TimeGenerated | datetime |  |
`;

describe('parseAzureMonitorTable', () => {
  test('parses name, categories and columns from a table doc', () => {
    const result = parseAzureMonitorTable(AZURE_FIXTURE);

    expect(result).toEqual({
      name: 'SigninLogs',
      categories: ['Azure Resources', 'Security'],
      columns: [
        { name: 'AADTenantId', type: 'string' },
        { name: 'ConditionalAccessStatus', type: 'string' },
        { name: 'DeviceDetail', type: 'dynamic' },
        { name: 'TimeGenerated', type: 'datetime' },
      ],
    });
  });

  test('defaults a blank type to unknown', () => {
    const md = '# T\n\n## Columns\n\n| Column | Type | Description |\n|---|---|---|\n| Weird |  | no type |\n';
    expect(parseAzureMonitorTable(md).columns).toEqual([{ name: 'Weird', type: 'unknown' }]);
  });

  test('returns empty categories when the attributes row is absent', () => {
    const md = '# T\n\n## Columns\n\n| Column | Type | Description |\n|---|---|---|\n| A | string |  |\n';
    expect(parseAzureMonitorTable(md).categories).toEqual([]);
  });

  test('returns null when there is no Columns section', () => {
    expect(parseAzureMonitorTable('# JustAHeading\n\nSome prose.\n')).toBeNull();
  });

  test('returns null when there is no H1', () => {
    expect(parseAzureMonitorTable('## Columns\n\n| Column | Type |\n|---|---|\n| A | string |\n')).toBeNull();
  });

  test('returns null when the Columns section has an empty table', () => {
    expect(parseAzureMonitorTable('# T\n\n## Columns\n\n| Column | Type | Description |\n|---|---|---|\n')).toBeNull();
  });
});
