import { describe, expect, test } from 'vitest';
import { parseAzureMonitorTable, parseDefenderTable, buildImportRows } from '../fetch-schemas.js';

// Modelled on the real generated format of
// azure-monitor-docs/articles/azure-monitor/reference/tables/signinlogs.md.
const AZURE_FIXTURE = `---
title: Azure Monitor Logs reference - SigninLogs
ms.topic: generated-reference

# This file is automatically generated. Changes will be overwritten. Do not change this file directly.
---

# SigninLogs

## Table attributes

|Attribute|Value|
|---|---|
|**Resource types**|microsoft.graph/tenants|
|**Categories**|Azure Resources, Security|
|**Solutions**| LogManagement|

## Columns

| Column | Type | Description |
|---|---|---|
| AADTenantId | string |   |
| ConditionalAccessStatus | string | The status of the conditional access policy triggered. |
| DeviceDetail | dynamic | The device information from where the sign-in occurred. |
| TimeGenerated | datetime |  |
`;

describe('parseAzureMonitorTable', () => {
  test('parses name, categories and columns from a table doc', () => {
    const result = parseAzureMonitorTable(AZURE_FIXTURE);

    expect(result).toEqual({
      name: 'SigninLogs',
      categories: ['Azure Resources', 'Security'],
      columns: [
        { name: 'AADTenantId', type: 'string' },
        { name: 'ConditionalAccessStatus', type: 'string' },
        { name: 'DeviceDetail', type: 'dynamic' },
        { name: 'TimeGenerated', type: 'datetime' },
      ],
    });
  });

  test('defaults a blank type to unknown', () => {
    const md = '# T\n\n## Columns\n\n| Column | Type | Description |\n|---|---|---|\n| Weird |  | no type |\n';
    expect(parseAzureMonitorTable(md).columns).toEqual([{ name: 'Weird', type: 'unknown' }]);
  });

  test('returns empty categories when the attributes row is absent', () => {
    const md = '# T\n\n## Columns\n\n| Column | Type | Description |\n|---|---|---|\n| A | string |  |\n';
    expect(parseAzureMonitorTable(md).categories).toEqual([]);
  });

  test('returns null when there is no Columns section', () => {
    expect(parseAzureMonitorTable('# JustAHeading\n\nSome prose.\n')).toBeNull();
  });

  test('returns null when there is no H1', () => {
    expect(parseAzureMonitorTable('## Columns\n\n| Column | Type |\n|---|---|\n| A | string |\n')).toBeNull();
  });

  test('returns null when the Columns section has an empty table', () => {
    expect(parseAzureMonitorTable('# T\n\n## Columns\n\n| Column | Type | Description |\n|---|---|---|\n')).toBeNull();
  });
});

// Modelled on the real format of defender-docs/defender-xdr/advanced-hunting-deviceevents-table.md.
const DEFENDER_FIXTURE = `---
title: DeviceEvents table in the advanced hunting schema
ms.topic: reference
---

# DeviceEvents

[!INCLUDE [Microsoft Defender XDR rebranding](../includes/microsoft-defender.md)]

The miscellaneous device events or \`DeviceEvents\` table in the [advanced hunting](advanced-hunting-overview.md) schema contains information about various event types. Use this reference to construct queries.

> [!TIP]
> For detailed information, use the built-in schema reference.

| Column name | Data type | Description |
|-------------|-----------|-------------|
| \`Timestamp\` | \`datetime\` | Date and time when the event was recorded |
| \`DeviceId\` | \`string\` | Unique identifier for the device in the service |
| \`ActionType\` | \`string\` | Type of activity that triggered the event |
`;

describe('parseDefenderTable', () => {
  test('parses name, description and backticked columns', () => {
    const result = parseDefenderTable(DEFENDER_FIXTURE);

    expect(result.name).toBe('DeviceEvents');
    expect(result.description).toBe(
      'The miscellaneous device events or DeviceEvents table in the advanced hunting schema contains information about various event types. Use this reference to construct queries.',
    );
    expect(result.columns).toEqual([
      { name: 'Timestamp', type: 'datetime' },
      { name: 'DeviceId', type: 'string' },
      { name: 'ActionType', type: 'string' },
    ]);
  });

  test('returns an empty description when only directives precede the table', () => {
    const md = '# T\n\n[!INCLUDE [x](y.md)]\n\n| Column name | Data type | Description |\n|---|---|---|\n| `A` | `string` |  |\n';
    const result = parseDefenderTable(md);
    expect(result.description).toBe('');
    expect(result.columns).toEqual([{ name: 'A', type: 'string' }]);
  });

  test('returns null for a function doc with no columns table', () => {
    const md = '# AssignedIPAddresses()\n\nThe function returns addresses. No table here.\n';
    expect(parseDefenderTable(md)).toBeNull();
  });

  test('strips a trailing (Preview) suffix from the H1 name', () => {
    const md = '# AgentsInfo (Preview)\n\n| Column name | Data type | Description |\n|---|---|---|\n| `DeviceId` | `string` |  |\n';
    expect(parseDefenderTable(md).name).toBe('AgentsInfo');
  });

  test('skips a leading non-columns pipe table and finds the real one', () => {
    const md = [
      '# T',
      '',
      '| Attribute | Value |',
      '|---|---|',
      '| Foo | Bar |',
      '',
      '| Column name | Data type | Description |',
      '|-------------|-----------|-------------|',
      '| `A` | `string` | desc |',
      '',
    ].join('\n');
    expect(parseDefenderTable(md).columns).toEqual([{ name: 'A', type: 'string' }]);
  });
});

const col = (name) => ({ name, type: 'string' });

describe('buildImportRows', () => {
  const azureSecurity = { name: 'SecurityEvent', categories: ['Security'], columns: [col('EventID')] };
  const azureNonSecurity = { name: 'ADTDigitalTwinsOperation', categories: ['Azure Resources'], columns: [col('OperationName')] };
  const azureKnownNonSecurity = { name: 'Heartbeat', categories: ['Virtual Machines'], columns: [col('Computer')] };
  const defenderTable = {
    name: 'DeviceEvents',
    description: 'Miscellaneous device events.',
    columns: [col('Timestamp')],
  };
  const build = (overrides = {}) =>
    buildImportRows({
      azure: [azureSecurity, azureNonSecurity, azureKnownNonSecurity],
      defender: [defenderTable],
      sentinelTableNames: ['Heartbeat'],
      scrapeDate: '2026-08-02',
      ...overrides,
    });

  test('keeps Security-category and SENTINEL_TABLES tables, drops the rest', () => {
    const { rows } = build();
    expect(rows.map((r) => r.name)).toEqual(['DeviceEvents', 'Heartbeat', 'SecurityEvent']);
  });

  test('composes Log Analytics notes from categories, docs URL and scrape date', () => {
    const { rows } = build();
    expect(rows.find((r) => r.name === 'SecurityEvent').notes).toBe(
      'Categories: Security\n' +
        'https://learn.microsoft.com/azure/azure-monitor/reference/tables/securityevent\n' +
        'Scraped from Microsoft Learn on 2026-08-02.',
    );
  });

  test('composes Defender notes from description, docs URL and scrape date', () => {
    const { rows } = build();
    expect(rows.find((r) => r.name === 'DeviceEvents').notes).toBe(
      'Miscellaneous device events.\n' +
        'https://learn.microsoft.com/defender-xdr/advanced-hunting-deviceevents-table\n' +
        'Scraped from Microsoft Learn on 2026-08-02.',
    );
  });

  test('on a name collision the Defender columns win and the note says so', () => {
    const sentinelCopy = { name: 'DeviceEvents', categories: ['Security'], columns: [col('TimeGenerated')] };
    const { rows } = build({ azure: [sentinelCopy] });
    const row = rows.find((r) => r.name === 'DeviceEvents');
    expect(row.columns).toEqual([col('Timestamp')]);
    expect(row.notes).toContain("Sentinel's streamed copy of this table also carries TimeGenerated.");
  });

  test('no collision line when only the Defender source has the table', () => {
    const { rows } = build();
    expect(rows.find((r) => r.name === 'DeviceEvents').notes).not.toContain('streamed copy');
  });

  test('truncates past 500 columns with a warning and a note line', () => {
    const wide = {
      name: 'WideTable',
      categories: ['Security'],
      columns: Array.from({ length: 512 }, (_, i) => col(`C${i}`)),
    };
    const { rows, warnings } = build({ azure: [wide] });
    const row = rows.find((r) => r.name === 'WideTable');
    expect(row.columns).toHaveLength(500);
    expect(row.notes).toContain('Column list truncated to 500 of 512 columns.');
    expect(warnings).toEqual(['WideTable: 512 columns, truncated to 500']);
  });

  test('truncates notes at 5000 characters', () => {
    const chatty = { name: 'ChattyTable', description: 'x'.repeat(6000), columns: [col('A')] };
    const { rows } = build({ defender: [defenderTable, chatty] });
    expect(rows.find((r) => r.name === 'ChattyTable').notes).toHaveLength(5000);
  });

  test('does not mutate its inputs', () => {
    const before = JSON.parse(JSON.stringify(azureSecurity));
    build();
    expect(azureSecurity).toEqual(before);
  });

  test('keeps the column-truncation notice intact even when notes are near the limit', () => {
    const wideAndChatty = {
      name: 'WideAndChatty',
      description: 'x'.repeat(6000),
      columns: Array.from({ length: 512 }, (_, i) => col(`C${i}`)),
    };
    const { rows } = build({ defender: [wideAndChatty] });
    const row = rows.find((r) => r.name === 'WideAndChatty');
    expect(row.columns).toHaveLength(500);
    expect(row.notes.length).toBeLessThanOrEqual(5000);
    expect(row.notes).toContain('Column list truncated to 500 of 512 columns.');
  });
});
