// ---------------------------------------------------------------------------
// Emits the security-relevant Microsoft table schemas as the bare JSON array
// the Schemas tab importer accepts. Sources are the generated markdown behind
// learn.microsoft.com; see docs/superpowers/specs/2026-08-02-table-schema-scraper-design.md.
//
//   node scripts/fetch-schemas.js [output-path]     # default ./table-schemas.json
// ---------------------------------------------------------------------------

// Parses `| Name | type | description |` rows from the first markdown table in
// `section`. The first `|` line is the header, `|---|` separators are skipped,
// and the table ends at the first non-`|` line after it started — later tables
// in the same section (e.g. ActionType value lists) are ignored.
function parseMarkdownColumnRows(section) {
  const columns = [];
  let inTable = false;
  for (const line of section.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed.startsWith('|')) {
      if (inTable) break;
      continue;
    }
    const cells = trimmed.split('|').slice(1, -1).map((cell) => cell.trim());
    if (cells.length < 2) continue;
    if (!inTable) {
      inTable = true; // header row
      continue;
    }
    if (/^:?-{2,}/.test(cells[0])) continue; // |---|---| separator
    const name = cells[0].replace(/`/g, '').trim();
    if (!name) continue;
    const type = cells[1].replace(/`/g, '').trim() || 'unknown';
    columns.push({ name, type });
  }
  return columns;
}

// The generated docs carry a `# This file is automatically generated...`
// comment INSIDE the YAML frontmatter, which a naive /^# / H1 match would
// mistake for the table name — so the frontmatter goes first.
function stripFrontmatter(markdown) {
  return markdown.replace(/^---\n[\s\S]*?\n---\n/, '');
}

// One azure-monitor-docs table doc -> { name, categories, columns }, or null
// for files that are not table references (no H1 or no Columns table).
function parseAzureMonitorTable(rawMarkdown) {
  const markdown = stripFrontmatter(rawMarkdown);
  const nameMatch = markdown.match(/^# (.+)$/m);
  if (!nameMatch) return null;

  const categoriesMatch = markdown.match(/^\|\s*\*\*Categories\*\*\s*\|([^|]*)\|/m);
  const categories = categoriesMatch
    ? categoriesMatch[1].split(',').map((c) => c.trim()).filter(Boolean)
    : [];

  const columnsSection = markdown.split(/^## Columns\s*$/m)[1];
  if (!columnsSection) return null;
  const columns = parseMarkdownColumnRows(columnsSection);
  if (columns.length === 0) return null;

  return { name: nameMatch[1].trim(), categories, columns };
}

// First real prose paragraph of `text`: skips [!INCLUDE]/[!TIP] directives,
// blockquotes, headings, tables and blank blocks; flattens [text](url) links
// to their text and strips backticks, because notes are plain text.
function firstProseParagraph(text) {
  for (const block of text.split(/\n\s*\n/)) {
    const trimmed = block.trim();
    if (!trimmed) continue;
    if (/^(\[!|>|#|\|)/.test(trimmed)) continue;
    return trimmed
      .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
      .replace(/`/g, '')
      .replace(/\s+/g, ' ')
      .trim();
  }
  return '';
}

// One defender-docs advanced-hunting-*-table.md -> { name, description, columns },
// or null for docs with no columns table (the -function.md pages, mainly).
function parseDefenderTable(rawMarkdown) {
  const markdown = stripFrontmatter(rawMarkdown);
  const nameMatch = markdown.match(/^# (.+)$/m);
  if (!nameMatch) return null;

  const afterH1 = markdown.slice(markdown.indexOf(nameMatch[0]) + nameMatch[0].length);
  const columns = parseMarkdownColumnRows(afterH1);
  if (columns.length === 0) return null;

  return {
    name: nameMatch[1].replace(/`/g, '').trim(),
    description: firstProseParagraph(afterH1),
    columns,
  };
}

export { parseAzureMonitorTable, parseMarkdownColumnRows, parseDefenderTable, firstProseParagraph };
