// ---------------------------------------------------------------------------
// Emits the security-relevant Microsoft table schemas as the bare JSON array
// the Schemas tab importer accepts. Sources are the generated markdown behind
// learn.microsoft.com; see docs/superpowers/specs/2026-08-02-table-schema-scraper-design.md.
//
//   node scripts/fetch-schemas.js [output-path]     # default ./table-schemas.json
// ---------------------------------------------------------------------------

import { execFileSync } from 'node:child_process';
import { mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SENTINEL_TABLES } from '../src/constants.js';

// Parses `| Name | type | description |` rows from the first markdown table in
// `section`. The first `|` line is the header, `|---|` separators are skipped,
// and the table ends at the first non-`|` line after it started — later tables
// in the same section (e.g. ActionType value lists) are ignored.
function parseMarkdownColumnRows(section) {
  const columns = [];
  let inTable = false;
  for (const line of section.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed.startsWith('|')) {
      if (inTable) break;
      continue;
    }
    const cells = trimmed.split('|').slice(1, -1).map((cell) => cell.trim());
    if (cells.length < 2) continue;
    if (!inTable) {
      inTable = true; // header row
      continue;
    }
    if (/^:?-{2,}/.test(cells[0])) continue; // |---|---| separator
    const name = cells[0].replace(/`/g, '').trim();
    if (!name) continue;
    const type = cells[1].replace(/`/g, '').trim() || 'unknown';
    columns.push({ name, type });
  }
  return columns;
}

// The generated docs carry a `# This file is automatically generated...`
// comment INSIDE the YAML frontmatter, which a naive /^# / H1 match would
// mistake for the table name — so the frontmatter goes first.
function stripFrontmatter(markdown) {
  return markdown.replace(/^---\n[\s\S]*?\n---\n/, '');
}

// One azure-monitor-docs table doc -> { name, categories, columns }, or null
// for files that are not table references (no H1 or no Columns table).
function parseAzureMonitorTable(rawMarkdown) {
  const markdown = stripFrontmatter(rawMarkdown);
  const nameMatch = markdown.match(/^# (.+)$/m);
  if (!nameMatch) return null;

  const categoriesMatch = markdown.match(/^\|\s*\*\*Categories\*\*\s*\|([^|]*)\|/m);
  const categories = categoriesMatch
    ? categoriesMatch[1].split(',').map((c) => c.trim()).filter(Boolean)
    : [];

  const columnsSection = markdown.split(/^## Columns\s*$/m)[1];
  if (!columnsSection) return null;
  const columns = parseMarkdownColumnRows(columnsSection);
  if (columns.length === 0) return null;

  return { name: nameMatch[1].trim(), categories, columns };
}

// First real prose paragraph of `text`: skips [!INCLUDE]/[!TIP] directives,
// blockquotes, headings, tables and blank blocks; flattens [text](url) links
// to their text and strips backticks, because notes are plain text.
function firstProseParagraph(text) {
  for (const block of text.split(/\n\s*\n/)) {
    const trimmed = block.trim();
    if (!trimmed) continue;
    if (/^(\[!|>|#|\|)/.test(trimmed)) continue;
    return trimmed
      .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
      .replace(/`/g, '')
      .replace(/\s+/g, ' ')
      .trim();
  }
  return '';
}

// One defender-docs advanced-hunting-*-table.md -> { name, description, columns },
// or null for docs with no columns table (the -function.md pages, mainly).
function parseDefenderTable(rawMarkdown) {
  const markdown = stripFrontmatter(rawMarkdown);
  const nameMatch = markdown.match(/^# (.+)$/m);
  if (!nameMatch) return null;

  const afterH1 = markdown.slice(markdown.indexOf(nameMatch[0]) + nameMatch[0].length);
  const columns = parseMarkdownColumnRows(afterH1);
  if (columns.length === 0) return null;

  return {
    name: nameMatch[1].replace(/`/g, '').trim(),
    description: firstProseParagraph(afterH1),
    columns,
  };
}

// Bounds copied from LIMITS in api/validate.js — the import must survive
// PUT /api/schemas/:name validation unchanged.
const MAX_COLUMNS = 500;
const MAX_NOTES = 5000;

// Applies the selection filter (Security category or a known Sentinel table),
// the Defender-wins collision rule, notes composition and the API bounds.
// Returns { rows, warnings } — rows sorted by name, warnings for the summary.
function buildImportRows({ azure, defender, sentinelTableNames, scrapeDate }) {
  const scrapeLine = `Scraped from Microsoft Learn on ${scrapeDate}.`;
  const byName = new Map();

  for (const table of azure) {
    const isSecurity = table.categories.includes('Security');
    if (!isSecurity && !sentinelTableNames.includes(table.name)) continue;
    const notes = [
      table.categories.length ? `Categories: ${table.categories.join(', ')}` : null,
      `https://learn.microsoft.com/azure/azure-monitor/reference/tables/${table.name.toLowerCase()}`,
      scrapeLine,
    ].filter(Boolean).join('\n');
    byName.set(table.name, { name: table.name, columns: table.columns, notes });
  }

  for (const table of defender) {
    const collided = byName.has(table.name);
    const notes = [
      table.description || null,
      `https://learn.microsoft.com/defender-xdr/advanced-hunting-${table.name.toLowerCase()}-table`,
      scrapeLine,
      collided ? "Sentinel's streamed copy of this table also carries TimeGenerated." : null,
    ].filter(Boolean).join('\n');
    byName.set(table.name, { name: table.name, columns: table.columns, notes });
  }

  const warnings = [];
  const rows = [...byName.values()]
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((row) => {
      let { columns, notes } = row;
      if (columns.length > MAX_COLUMNS) {
        warnings.push(`${row.name}: ${columns.length} columns, truncated to ${MAX_COLUMNS}`);
        const notice = `Column list truncated to ${MAX_COLUMNS} of ${columns.length} columns.`;
        const noticeWithNewline = `\n${notice}`;
        // Reserve space for the notice and ensure it survives the MAX_NOTES truncation
        if (notes.length + noticeWithNewline.length > MAX_NOTES) {
          notes = notes.slice(0, MAX_NOTES - noticeWithNewline.length) + noticeWithNewline;
        } else {
          notes = notes + noticeWithNewline;
        }
        columns = columns.slice(0, MAX_COLUMNS);
      }
      if (notes.length > MAX_NOTES) notes = notes.slice(0, MAX_NOTES);
      return { name: row.name, columns, notes };
    });

  return { rows, warnings };
}

const SOURCES = {
  azure: {
    repo: 'https://github.com/MicrosoftDocs/azure-monitor-docs.git',
    sparsePath: 'articles/azure-monitor/reference/tables',
  },
  defender: {
    repo: 'https://github.com/MicrosoftDocs/defender-docs.git',
    sparsePath: 'defender-xdr',
  },
};

// Shallow sparse clone: two git commands instead of ~1,200 rate-limited HTTP
// fetches. Returns the checked-out sparse dir. The temp root is registered in
// cloneRoots immediately after creation — before either git command runs — so
// a git failure (network, bad URL, sparse-checkout) still leaves the partial
// clone dir queued for the caller's cleanup instead of leaking it.
function cloneSparse({ repo, sparsePath }, cloneRoots) {
  const root = mkdtempSync(join(tmpdir(), 'kqlstore-schemas-'));
  cloneRoots.push(root);
  execFileSync('git', ['clone', '--depth', '1', '--filter=blob:none', '--sparse', '--quiet', repo, root], { stdio: 'inherit' });
  execFileSync('git', ['-C', root, 'sparse-checkout', 'set', sparsePath], { stdio: 'inherit' });
  return { dir: join(root, sparsePath), root };
}

function parseDirectory(dir, filePattern, parse) {
  const parsed = [];
  const skipped = [];
  for (const file of readdirSync(dir).filter((f) => filePattern.test(f))) {
    const result = parse(readFileSync(join(dir, file), 'utf8'));
    if (result) parsed.push(result);
    else skipped.push(file);
  }
  return { parsed, skipped };
}

function main() {
  const outPath = process.argv[2] ?? './table-schemas.json';
  const scrapeDate = new Date().toISOString().slice(0, 10);
  const cloneRoots = [];
  try {
    console.log('Cloning MicrosoftDocs/azure-monitor-docs (sparse)...');
    const azureClone = cloneSparse(SOURCES.azure, cloneRoots);
    const azure = parseDirectory(azureClone.dir, /\.md$/, parseAzureMonitorTable);

    console.log('Cloning MicrosoftDocs/defender-docs (sparse)...');
    const defenderClone = cloneSparse(SOURCES.defender, cloneRoots);
    const defender = parseDirectory(
      defenderClone.dir,
      /^advanced-hunting-.+-table\.md$/,
      parseDefenderTable,
    );

    const { rows, warnings } = buildImportRows({
      azure: azure.parsed,
      defender: defender.parsed,
      sentinelTableNames: SENTINEL_TABLES,
      scrapeDate,
    });

    writeFileSync(outPath, `${JSON.stringify(rows, null, 2)}\n`);

    for (const warning of warnings) console.warn(`warning: ${warning}`);
    const skipped = [...azure.skipped.map((f) => `azure:${f}`), ...defender.skipped.map((f) => `defender:${f}`)];
    console.log(`${rows.length} tables written to ${outPath} (${azure.parsed.length} Log Analytics docs parsed, ${defender.parsed.length} Defender).`);
    if (skipped.length) console.log(`${skipped.length} files skipped (no parseable schema): ${skipped.join(', ')}`);
  } finally {
    for (const root of cloneRoots) rmSync(root, { recursive: true, force: true });
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();

export { parseAzureMonitorTable, parseMarkdownColumnRows, parseDefenderTable, firstProseParagraph, buildImportRows };
